/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare global {
  const RouterLink = {} as typeof import('vue-router/auto')['RouterLink']
  const RouterView = {} as typeof import('vue-router/auto')['RouterView']
  const TheCounter = {} as typeof import('./src/components/TheCounter.setup.tsx')['default']
  const TheFooter = {} as typeof import('./src/components/TheFooter.setup.tsx')['default']
  const TheInput = {} as typeof import('./src/components/TheInput.setup.tsx')['default']
}
